apiVersion: v1
kind: Service
metadata:
  name: honepad-db-service
  namespace: honepad
spec:
  selector:
    app: honepad-db
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30027
