apiVersion: v1
kind: Service
metadata:
  name: notepad-db-service
  namespace: notepad
spec:
  selector:
    app: notepad-db
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30027
